### ISSUE TITLE
Possibility to change favicons

### ISSUE THREAD

**Issue by aschilling** [lformella/rss-extender#21]
Hi,

I like rss-extender a lot. Is there any possibility to change the favicons of an extended feed? I use rss-extender together with Yahoo Pipes which overwrites each feed with its own favicon.

Thanks in advance

Andy

**Comment by Strubbl** [comment]
Sorry, I don't know of any possibilty. I guess the Favicon is received through your RSS client directly from the the RSS'ed website. So maybe you have an influence on the chosen favicon in your RSS client.
