### ISSUE TITLE
Useable feed for iphoneblog

### ISSUE THREAD

**Issue by aschilling** [lformella/rss-extender#23]
Hi Lars,

I like RSS-Extender a lot and still use it every day. However, I have some problems producing a useable feed for iphoneblog.de. My config looks like this:

    <?php
    $config['url']                  = "http://www.iphoneblog.de/feed/"; 
    $config['base_url']             = "http://www.iphoneblog.de/"; 
    $config['content']              = array("<div class=\"beitragstext\">(.*)<div class=\"beitragsmedia\">", 1);
    $config['search ']              = array("#<ads>.*<\/ads>#Uis",
                                        "&nbsp;",
                                        "<div class=\"beitragsmedia\">");
    $config['replace']              = array("",
                                        " ",
                                        "");
    ?>

However, the config does not work, because there are still some '&nbsp' tokens in the text. How can this be? Moreover, is there any way how to block the ads from feedsportal in this feed using RSS-Extender?

Cheers

Andy

**Comment by Strubbl** [comment]
You have a space in the arrey key name. Look more closely at 
```$config['search ']```
The space after the word search. Removing this might solve this issue. 

If it still occurs, please reopen this issue. You can also provide your working config via PR.
