### ISSUE TITLE
Heise feeds no longer displaying images

### ISSUE THREAD

**Issue by aschilling** [lformella/rss-extender#24]
Hi Lars,

I really like RSS Extender a lot and use it everyday, however, since two weeks the heise feeds are no longer extracting the images correctly. For example in the post:

http://www.heise.de/newsticker/meldung/Windows-10-Upgrade-Installation-auch-von-Windows-7-aus-moeglich-2438050.html/from/atom10?wt_mc=rss.ho.beitrag.atom

RSS Extender extracts the image path as: 
http://www.heise.de/newsticker/meldung/Windows-10-Upgrade-Installation-auch-von-Windows-7-aus-moeglich-2438050.html?view=zoom;zoom=1

while it should be:
http://2.f.ix.de/imgs/18/1/3/6/9/8/1/0/upgrader-a8c02cd6e11f7516.png

I would deeply appreciate your help

Andy

**Comment by Strubbl** [comment]
Heise images are working afaik. --> I close this issue
