### ISSUE TITLE
sueddeutsche-top.php  seems to be broken

### ISSUE THREAD

**Issue by huggenknubbel** [lformella/rss-extender#34]
Hello, 
i got:  "Your Rss-Extender rules returned an empty string for link"

maybe a little tutorial to fix that pages for my own would be nice :)

**Comment by Strubbl** [comment]
You can apply the regex from the according config to the source code of a web page you want to extend by using e.g. https://regex101.com/

It would be cool to see a pull request for a fix. :)

**Comment by huggenknubbel** [comment]
Sorry i am really don't know what to do there.
I'm not a dev.

**Comment by Strubbl** [comment]
okay, if i have some time and a PC with a keyboard, i am going to have a look into this issue. but currently i am on vacation and i do not use this feed.

**Comment by Strubbl** [comment]
@huggenknubbel can you please test the current release on master branch?
