### ISSUE TITLE
Integrate readability.php

### ISSUE THREAD

**Issue by pnhofmann** [lformella/rss-extender#49]
[Readability.php ](https://github.com/andreskrey/readability.php) analyses any html site and tries to extract relevant content. It is ported from Mozilla's Readability.js, which is used by firefox "reader view".

I noticed this could also be used for RSS extension:

* As a fallback if Regex rules fail / return empty text
* For feeds with no configured regex (yet) to get maybe not 100% perfect, but basic extension
* For news aggregators, which link to lots of different sites where no one can create regex for

Of course everything should optional.

In fact, I already implemented everything above for personal use. Quick and dirty - but if someone wants to take [a look](https://github.com/pnhofmann/rss-extender/tree/publish_github) - but don't loot too close ;).

Any interest in those patches?

I really just wrote them for personal use - so no problem at all if you say no. If you are interested, I would clean up my mess, refactor the patches and create a PR. Otherwise just close this issue.

**Comment by Strubbl** [comment]
That's sounds like a very cool idea. If you want to share your patches i'll be happy to merge them.

**Comment by Strubbl** [comment]
Closing this issue since #50 has been merged.
